export enum TimeOffRequestStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVAL_IN_PROGRESS = 'APPROVAL_IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  REQUIRES_RECONCILIATION = 'REQUIRES_RECONCILIATION',
}

export const ACTIVE_HOLD_STATUSES = [
  TimeOffRequestStatus.PENDING_APPROVAL,
  TimeOffRequestStatus.APPROVAL_IN_PROGRESS,
  TimeOffRequestStatus.REQUIRES_RECONCILIATION,
];

export enum HcmCommandStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN',
}

export enum HcmCommandType {
  BOOK_TIME_OFF = 'BOOK_TIME_OFF',
}
